In [63]:
import numpy as np

In [64]:
myarr = np.array([4,5,7], np.int8)

In [65]:
myarr

array([4, 5, 7], dtype=int8)

In [66]:
myarr1 = np.array([[1,2,3],[4,5,6]])


In [67]:
myarr1[1,1]

5

In [68]:
myarr1.shape

(2, 3)

In [69]:
#Change elemnet of Matrix
myarr1[1,2]=23

In [70]:
myarr1

array([[ 1,  2,  3],
       [ 4,  5, 23]])

In [71]:
myarr1.size

6

In [72]:
Zero = np.zeros((2,5))
Zero


array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [73]:
Zero.shape


(2, 5)

In [74]:
Zero.size

10

In [75]:
#Range Array
Range = np.arange(0,20)
Range


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [76]:
lspace = np.linspace(1, 100, 10)
lspace

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

In [77]:
#Empty array

Empty = np.empty((2,3))
Empty

array([[1.28625394e+248, 1.70179369e+300, 3.95614168e+252],
       [1.65023927e+137, 1.24551397e+272, 9.71410839e-315]])

In [78]:
#identity array

Iden = np.identity(3)
Iden


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [79]:
#reshape array

Reshape = np.array([1,2,3,4,5,6,7,8,9,10])
arr = Reshape.reshape(2,5)
arr


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [80]:
#ravel array
arr = arr.ravel()
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [81]:
ar = ([1,2,3],[4,5,6],[7,8,9])

In [82]:
ar = np.array(ar)
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [83]:
ar.sum(axis=0)

array([12, 15, 18])

In [84]:
ar.sum(axis=1)

array([ 6, 15, 24])

In [85]:
#Transpose array
ar.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [86]:
ar.ndim

2

In [87]:
Ary = np.array([1,2,3,40,5,6,7,8,9,10])


In [88]:
Ary.argmax()

3

In [89]:
Ary.argmin()

0

In [90]:
Ary.argsort()

array([0, 1, 2, 4, 5, 6, 7, 8, 9, 3], dtype=int64)

In [95]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [97]:
ar.argmax(axis=1)

array([2, 2, 2], dtype=int64)

In [99]:
ar.argmin(axis=0)


array([0, 0, 0], dtype=int64)

In [100]:
ar.argsort(axis=1)

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]], dtype=int64)

In [101]:
Ary

array([ 1,  2,  3, 40,  5,  6,  7,  8,  9, 10])

In [103]:
Ary.reshape(10,1)

array([[ 1],
       [ 2],
       [ 3],
       [40],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]])

In [107]:
x = ([4,4,6],[567,9,78],[66,9,7])

In [108]:
ar2=np.array(x)

In [109]:
ar2

array([[  4,   4,   6],
       [567,   9,  78],
       [ 66,   9,   7]])

In [110]:
ar3=ar+ar2

In [111]:
ar3

array([[  5,   6,   9],
       [571,  14,  84],
       [ 73,  17,  16]])

In [112]:
ar4=ar*ar3

In [113]:
ar4

array([[   5,   12,   27],
       [2284,   70,  504],
       [ 511,  136,  144]])

In [114]:
np.sqrt(ar4)

array([[ 2.23606798,  3.46410162,  5.19615242],
       [47.79121258,  8.36660027, 22.44994432],
       [22.60530911, 11.66190379, 12.        ]])

In [115]:
np.max(ar4)

2284

In [116]:
np.min(ar4)

5

In [118]:
np.sum(ar4)

3693

In [119]:
np.where(ar4>300)

(array([1, 1, 2], dtype=int64), array([0, 2, 0], dtype=int64))

In [120]:
np.count_nonzero(ar4)

9

In [121]:
np.nonzero(ar4)

(array([0, 0, 0, 1, 1, 1, 2, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1, 2], dtype=int64))

In [127]:
import sys


In [123]:
py_ar=[1,2,3,4,5,6,7,8,9,10]

In [124]:
np_ar=np.array(py_ar)

In [128]:
sys.getsizeof(1)*len(py_ar)

280

In [130]:
np_ar.itemsize * np_ar.size

40